export type Intent = 
    | 'GET_ANNOUNCEMENTS'
    | 'GET_ANNOUNCEMENTS_PUBLISHED'
    | 'GET_ANNOUNCEMENTS_MENTIONED'
    | 'GET_CLASSROOMS'
    | 'GET_LESSONS'
    | 'UNKNOWN'

export const INTENT = {
  GET_ANNOUNCEMENTS: 'GET_ANNOUNCEMENTS',
  GET_ANNOUNCEMENTS_PUBLISHED: 'GET_ANNOUNCEMENTS_PUBLISHED',
  GET_ANNOUNCEMENTS_MENTIONED: 'GET_ANNOUNCEMENTS_MENTIONED',
  GET_CLASSROOMS: 'GET_CLASSROOMS',
  GET_LESSONS: 'GET_LESSONS',
  UNKNOWN: 'UNKNOWN',
} as const;